### ISSUE TITLE
Add instructions for launching project in browser using local host

### ISSUE THREAD

**Issue by isaacullah** [gamebeaker/marzipano-hotspot-view#2]
In the very helpful instructions you have already written, it would probably be good to add how to launch index.html using a local host, for example [nmp http-server](https://www.npmjs.com/package/http-server), so that you can see all the images when editing the viewpoints with your tool. It's very easy to do if you have nmp or npx installed. This would be at step 7. Change:

   7. Open your marzipano project in your browser

To:

   7. Open your marzipano project in your browser using a local host server, for example  [nmp http-server](https://www.npmjs.com/package/http-server). 
       If using http-server, you can launch it from the terminal in the app-files directory directly with:
      `npx http-server`
      Then you can point your browser to http://127.0.0.1:8080/ to view the project.

and then your original instructions can continue from there.

Thanks!

**Comment by gamebeaker** [comment]
@isaacullah Thanks for your contribution.
I am not sure if this should be in the scope of this project.
Why?
To use `npx` you need `npm` installed and i don't think "normal" user have this installed. The goal is to be user friendly for non-technical people.
To view the panorama created with marzipano tool you need a (local) server and i think that the user has figured this out as this question has a lot of answers on google.

I am going to add a hint that the user needs a server to view it in the browser.

**Comment by gamebeaker** [comment]
@isaacullah i am sorry i just tested your idea with `npx http-server` and it works easier than expected. I am going to add it to the instructions.

**Comment by isaacullah** [comment]
Glad you could add this! the `npx http-server` is by far the easiest and most cross-platform way that I've discovered to preview a static site from disk. Again, I really appreciate your work with this helpful tool!!
